class ProjectTemplates {
  /// Dependencies inserted into the generated project's pubspec.yaml.
  static const List<String> dependencies = [
    'flutter_riverpod: ^2.5.1',
    'riverpod_annotation: ^2.3.5',
    'auto_route: ^9.2.0',
    'skeletonizer: ^1.4.2',
    'slang: ^3.31.0',
    'slang_flutter: ^3.31.0',
    'retrofit: ^4.1.0',
    'dio: ^5.5.0',
    'freezed_annotation: ^2.4.4',
    'json_annotation: ^4.9.0',
  ];

  static const List<String> devDependencies = [
    'build_runner: ^2.4.11',
    'riverpod_generator: ^2.4.0',
    'auto_route_generator: ^9.2.0',
    'freezed: ^2.5.7',
    'json_serializable: ^6.8.0',
    'retrofit_generator: ^9.1.0',
    'slang_build_runner: ^3.31.0',
  ];

  static const analysisOptions = '''
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: false
''';

  /// lib/src/core/router/app_router.dart
  /// Includes comments on when/how to nest routes, as requested.
  static const appRouter = '''
import 'package:auto_route/auto_route.dart';

import '../../features/auth/presentation/screens/login_screen.dart';
import '../../features/auth/presentation/screens/register_screen.dart';
import '../../features/auth/presentation/screens/forgot_password_screen.dart';
import '../../features/home/presentation/screens/home_screen.dart';
import '../../features/details/presentation/screens/details_screen.dart';
import '../../features/profile/presentation/screens/profile_screen.dart';

part 'app_router.gr.dart';

@AutoRouterConfig()
class AppRouter extends \$AppRouter {
  @override
  List<AutoRoute> get routes => [
        // ── Standalone routes ────────────────────────────────────────────
        // Use a plain AutoRoute when the screen doesn't need to keep any
        // parent screen/state alive, and doesn't have "child" screens that
        // depend on it (most screens fall in this bucket).
        AutoRoute(page: LoginRoute.page, path: '/login', initial: true),
        AutoRoute(page: RegisterRoute.page, path: '/register'),
        AutoRoute(page: ForgotPasswordRoute.page, path: '/forgot-password'),
        AutoRoute(page: ProfileRoute.page, path: '/profile'),

        // ── Nested / children routes ─────────────────────────────────────
        // Use nested routes when a screen acts as a "parent" for others that
        // share its context or navigation stack — e.g. a list that pushes
        // into a detail view but should keep the list's scroll position /
        // state alive underneath, or a tab shell. The child's path is
        // RELATIVE to the parent and does NOT start with a slash.
        //
        // Example — a "chats" list with a nested "chat/:id" detail route,
        // reachable at /chats and /chats/123:
        //
        // AutoRoute(
        //   page: ChatsRoute.page,
        //   path: '/chats',
        //   children: [
        //     AutoRoute(page: ChatRoute.page, path: ':id'),
        //   ],
        // ),
        AutoRoute(page: HomeRoute.page, path: '/home'),
        AutoRoute(page: DetailsRoute.page, path: '/details/:id'),
      ];
}
''';

  /// lib/main.dart
  static const main = '''
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'src/core/router/app_router.dart';
import 'src/core/theme/app_theme.dart';
import 'src/core/i18n/strings.g.dart';

void main() {
  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final appRouter = AppRouter();

    return TranslationProvider(
      child: MaterialApp.router(
        title: 'My App',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.light,
        darkTheme: AppTheme.dark,
        themeMode: ThemeMode.system,
        routerConfig: appRouter.config(),
      ),
    );
  }
}
''';

  /// lib/src/core/theme/app_theme.dart — default theme, meant to be
  /// regenerated quickly per-project with `fsc theme`.
  static String theme({
    required String primaryHex,
    required String secondaryHex,
  }) {
    return '''
import 'package:flutter/material.dart';

/// Generated by fsc. Re-run `fsc theme --primary <hex> --secondary <hex>`
/// any time this app needs different brand colors — that's the only thing
/// that tends to differ between projects.
class AppTheme {
  AppTheme._();

  static const Color primaryColor = Color(0xFF$primaryHex);
  static const Color secondaryColor = Color(0xFF$secondaryHex);

  static ThemeData get light => _base(Brightness.light);
  static ThemeData get dark => _base(Brightness.dark);

  static ThemeData _base(Brightness brightness) {
    final colorScheme = ColorScheme.fromSeed(
      seedColor: primaryColor,
      secondary: secondaryColor,
      brightness: brightness,
    );

    return ThemeData(
      useMaterial3: true,
      colorScheme: colorScheme,
      appBarTheme: AppBarTheme(
        backgroundColor: colorScheme.surface,
        foregroundColor: colorScheme.onSurface,
        elevation: 0,
      ),
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          minimumSize: const Size.fromHeight(48),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
      ),
    );
  }
}
''';
  }

  /// assets/i18n/en.i18n.json — slang source of truth. Keys match what the
  /// screen templates reference (t.auth.login.title, etc).
  static const i18nEn = '''
{
  "auth": {
    "login": {
      "title": "Welcome back",
      "emailLabel": "Email",
      "passwordLabel": "Password",
      "forgotPassword": "Forgot password?",
      "submit": "Log in",
      "goToRegister": "Don't have an account? Sign up"
    },
    "register": {
      "title": "Create account",
      "nameLabel": "Name",
      "emailLabel": "Email",
      "passwordLabel": "Password",
      "submit": "Sign up"
    },
    "forgotPassword": {
      "title": "Reset password",
      "instructions": "Enter your email and we'll send you a link to reset your password.",
      "emailLabel": "Email",
      "submit": "Send reset link"
    },
    "errors": {
      "required": "This field is required"
    }
  },
  "home": {
    "title": "Home"
  },
  "details": {
    "title": "Details",
    "itemId": "Item ID"
  },
  "profile": {
    "title": "Profile",
    "editProfile": "Edit profile",
    "logout": "Log out"
  }
}
''';

  static const i18nEs = '''
{
  "auth": {
    "login": {
      "title": "Bienvenido de nuevo",
      "emailLabel": "Correo",
      "passwordLabel": "Contraseña",
      "forgotPassword": "¿Olvidaste tu contraseña?",
      "submit": "Iniciar sesión",
      "goToRegister": "¿No tienes cuenta? Regístrate"
    },
    "register": {
      "title": "Crear cuenta",
      "nameLabel": "Nombre",
      "emailLabel": "Correo",
      "passwordLabel": "Contraseña",
      "submit": "Registrarme"
    },
    "forgotPassword": {
      "title": "Restablecer contraseña",
      "instructions": "Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.",
      "emailLabel": "Correo",
      "submit": "Enviar enlace"
    },
    "errors": {
      "required": "Este campo es obligatorio"
    }
  },
  "home": {
    "title": "Inicio"
  },
  "details": {
    "title": "Detalles",
    "itemId": "ID del elemento"
  },
  "profile": {
    "title": "Perfil",
    "editProfile": "Editar perfil",
    "logout": "Cerrar sesión"
  }
}
''';

  static const slangConfig = '''
targets:
  - lib/src/core/i18n
input_directory: assets/i18n
input_file_pattern: .i18n.json
output_directory: lib/src/core/i18n
output_file_name: strings.g.dart
namespaces: false
fallback_strategy: base_locale
''';

  /// The shared auth controller/state used by login, register and
  /// forgot-password (they belong to the same feature and flow).
  static const authState = '''
import 'package:freezed_annotation/freezed_annotation.dart';

part 'auth_state.freezed.dart';

@freezed
class AuthState with _\$AuthState {
  const factory AuthState({
    @Default(false) bool isLoading,
    String? errorMessage,
  }) = _AuthState;
}
''';

  static const authController = '''
import 'package:riverpod_annotation/riverpod_annotation.dart';

import 'auth_state.dart';
// import '../../data/repositories/auth_repository.dart';

part 'auth_controller.g.dart';

@riverpod
class AuthController extends _\$AuthController {
  @override
  AuthState build() {
    return const AuthState();
  }

  // TODO: implement login / register / sendResetEmail / logout here,
  // delegating to an AuthRepository (generate one with:
  // `fsc generate repository Auth --feature auth`).
}
''';

  static String featureController(String featureLower, String featurePascal) => '''
import 'package:riverpod_annotation/riverpod_annotation.dart';

import '${featureLower}_state.dart';

part '${featureLower}_controller.g.dart';

@riverpod
class ${featurePascal}Controller extends _\$${featurePascal}Controller {
  @override
  ${featurePascal}State build() {
    return const ${featurePascal}State();
  }
}
''';

  static String featureState(String featureLower, String featurePascal) => '''
import 'package:freezed_annotation/freezed_annotation.dart';

part '${featureLower}_state.freezed.dart';

@freezed
class ${featurePascal}State with _\$${featurePascal}State {
  const factory ${featurePascal}State({
    @Default(false) bool isLoading,
    String? errorMessage,
  }) = _${featurePascal}State;
}
''';

  static const gitignoreExtra = '''

# fsc-managed
**/*.g.dart
**/*.freezed.dart
**/*.gr.dart
''';

  static const projectReadme = '''
# Next steps

This project was scaffolded with `fsc` (flutter_scaffold_cli).

1. `flutter pub get`
2. `dart run build_runner build --delete-conflicting-outputs`
   (needed for Riverpod, AutoRoute, Freezed and Slang codegen — re-run this
   any time you add/change a controller, repository, state or route)
3. `flutter run`

## What's included
- `lib/src/features/auth` → login, register, forgot password screens + shared `AuthController`
- `lib/src/features/home`, `details`, `profile` → one screen + controller/state each
- `lib/src/core/router/app_router.dart` → AutoRoute config, add new routes here
- `lib/src/core/theme/app_theme.dart` → regenerate anytime with `fsc theme --primary <hex> --secondary <hex>`
- `assets/i18n/*.i18n.json` → Slang translations (en/es included)

## Generating new repository/controller pairs
```
fsc generate repository User --feature user
fsc generate controller User --feature user --repository User
# or both at once, plus folder skeleton + screen stub:
fsc generate feature User
```
''';
}
